StudentRegMVC/Controllers/ClassStudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentRegMVC.Controllers
{
    public class ClassStudentController : Controller
    {
        AdvWebDevProjectEntities Contextobj = new AdvWebDevProjectEntities();
        // GET: ClassStudent
        public ActionResult Index()
        {

            return View();
        }

        // GET: ClassStudent/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClassStudent/Create
        public ActionResult Create(int studentid)
        {
            Models.ClassStudent obj = new Models.ClassStudent();
            return View();
        }

        // POST: ClassStudent/Create
        [HttpPost]
        public ActionResult Create(Models.ClassStudent obj)
        {
            try
            {
                // TODO: Add insert logic here


                Contextobj.ClassStudent.Add(new Class() { ClassId = obj.ClassId });
                Contextobj.SaveChanges();
                // TODO: Add insert logic here

                return RedirectToAction("Index");
               
            }
            catch
            {
                return View();
            }
        }

        // GET: ClassStudent/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ClassStudent/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ClassStudent/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ClassStudent/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

StudentRegMVC/Controllers/ClassesController.cs
using StudentRegMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Web.Services.Description;

namespace StudentRegMVC.Controllers
{
    public class ClassesController : Controller
    {
        AdvWebDevProjectEntities Contextobj = new AdvWebDevProjectEntities();

        // GET: Classes
        public ActionResult Index()
        {
            return View();
        }

        // GET: Classes/Create/add
        public ActionResult AddClass()
        {
            Models.Classes obj = new Models.Classes();
           obj.ClassDate = DateTime.Now;
            return View("AddClass", obj);
        }

        // POST: Classes/Create/Add
        [HttpPost]
        public ActionResult AddClass(Models.Classes obj)
        {


            Contextobj.ClassStudent.Add(new Class() { ClassId = obj.ClassId, ClassName = obj.ClassName, ClassDate = obj.ClassDate, ClassDescription = obj.ClassDescription });
            Contextobj.SaveChanges();
            // TODO: Add insert logic here

            //return RedirectToAction("Index");
            return RedirectToAction("AddClass", obj);
           
        }

        
        public ActionResult DisplayClasses()
        {

            IList<Class> ClassesRec = Contextobj.ClassStudent.ToList();
            return View("DisplayClasses", ClassesRec);

        }

        // GET: Classes/Edit/5
        public ActionResult EditClasses(int classid)
        {
            var ClassesRecord = (from item in Contextobj.ClassStudent
                                 where item.ClassId == classid
                                 select item).First();
            return View("EditClasses", ClassesRecord);

        }

        // POST: Classes/Edit/5
        [HttpPost]
        public ActionResult EditClasses(Classes obj)
        {
            try
            {
                var ClassesREcord = (from item in Contextobj.ClassStudent
                                     where item.ClassId == obj.ClassId
                                     select item).First();
                ClassesREcord.ClassId = obj.ClassId;
                ClassesREcord.ClassName = obj.ClassName;
                ClassesREcord.ClassDate = obj.ClassDate;
                ClassesREcord.ClassDescription = obj.ClassDescription;


                Contextobj.SaveChanges();

                var ClassesRecord = Contextobj.ClassStudent.ToList();
                return RedirectToAction("DisplayClasses", "Classes");


            }
            catch
            {
                return View("DisplayClasses", "Classes");
            }
        }

        //GET: Classes/Delete/5
        //public ActionResult DelClass(int classid)
        //{
        //    return View();
        //}

        // POST: Classes/Delete/5
        [HttpPost]
        public ActionResult DelClass(int classid)
        {
            try
            {
                // TODO: Add delete logic

                Class delclasses = Contextobj.ClassStudent.Find(classid);
                Contextobj.ClassStudent.Remove(delclasses);
                Contextobj.SaveChanges();
                return RedirectToAction("DisplayClasses", "Classes");
            }
            catch
            {
                return RedirectToAction("DisplayClasses", "Classes");
            }
        }

        //// GET: Classes/Select/5
        //[HttpPost]
        public ActionResult SelectClasses()
        {
            IList<Class> ClassesRec = Contextobj.ClassStudent.ToList();
            return View("SelectClasses", ClassesRec);
        }
        

    }

}

    
    

StudentRegMVC/Views/Classes/AddClass.cshtml
@{
    ViewBag.Title = "AddClass";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Add Class</h2>
@model StudentRegMVC.Models.Classes


<form action="AddClass/Classes" method="post">


    Class Id           :  @Html.TextBoxFor(model => model.ClassId)<br />
    Class Name         :  @Html.TextBoxFor(model => model.ClassName)<br />
    Class Date         :  @Html.TextBoxFor(model => model.ClassDate)<br />
    Class Description  :  @Html.TextBoxFor(model => model.ClassDescription)<br />


    @*<input type="text" login ="Loginid"  name="Name"/>*@


    <input type="submit" value="Add Class" />

</form>

StudentRegMVC/Views/Classes/DisplayClasses.cshtml
@*@{
    ViewBag.Title = "DisplayClasses";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<h2>DisplayClasses</h2>*@
@{
    ViewBag.Title = "DisplayClasses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model  List<Class>
<h2>Display Classes</h2>
     
<table border="1">
    <tr>
        <th>Class ID</th>
        <th>Class Name</th>
        <th>Class Date</th>        
        <th>Class Description</th>
        <th>Add</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>

                  @foreach (var item in Model)
                  {
    <tr>

        <td>@item.ClassId</td>
        <td>@item.ClassName</td>
        <td>@item.ClassDate</td>
        <td>@item.ClassDescription</td>

        <td>@Html.ActionLink("Add", "AddClass")</td>
        @*<td>    @using (Html.BeginForm("EditClasses", "Classes", new { classid = item.ClassId })) {<input type="submit" value="Edit"/> } </td>*@
        <td>@Html.ActionLink("Edit", "EditClasses", new { classid = item.ClassId })</td>
        @*<td>@Html.ActionLink("Del", "DelClasses", new { classid = item.ClassId })</td>*@
        <td>
            @using (Html.BeginForm("DelClass", "Classes", new { classid = item.ClassId }))
            {
                <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete record with ClassID=@item.ClassId')" />

            }


        </td>
                            

        

    </tr>     


                  }
                          @Html.ActionLink("Create New", "AddClass")
       
</table>

StudentRegMVC/Views/Classes/EditClasses.cshtml
@{
    ViewBag.Title = "EditClasses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Class
<h2>Edit Classes</h2>

<form action="EditClasses/Classes" method="post">


    Class  Id           :  @Html.TextBoxFor(model => model.ClassId)<br />
    Class Name          :  @Html.TextBoxFor(model => model.ClassName)<br />
    Class Date          :  @Html.TextBoxFor(model => model.ClassDate)<br />
    Class Description   :  @Html.TextBoxFor(model => model.ClassDescription)<br />
   

    @*<input type="text" login ="Loginid"  name="Name"/>*@


    <input type="submit" value="Update Class" />

</form>

StudentRegMVC/Views/Classes/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

StudentRegMVC/Views/Classes/SelectClasses.cshtml
@{
    ViewBag.Title = "SelectClasses";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<h2>Select Classes</h2>

< a href = "~/Models/ClassStudents.cs" > ~/ Models / ClassStudents.cs </ a >
<table border="1">
    <tr>
        <th>Class ID</th>
        <th>Student Id</th>
        >
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>@item.ClassId</td>
            <td>@item.Studentid</td>
            

            <td>@Html.ActionLink("Add", "AddClassStudent")</td>

            <td>@Html.ActionLink("Edit", "EditClassStudent", new { studentid = item.StudentId })</td>
            @*<td>@Html.ActionLink("Del", "DelClassStudent", new { classid = item.ClassId })</td>*@
            <td>
                @using (Html.BeginForm("DelClassStudent", "ClassStudent", new { studentid = item.StudentId }))
                {
                    <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete record with StudentID=@item.StudentId')" />

                }


            </td>

        </tr>
    }
    @Html.ActionLink("Create New", "AddClassStudent")

</table>